import {utils} from '@start9labs/start-sdk'
import {sdk} from '../sdk'
import {store} from '../fileModels/store'
import {i18n} from '../i18n'
const spec=sdk.InputSpec.of({regtest:sdk.Value.toggle({name:i18n("Use regtest (advanced)"),default:false}),pruned:sdk.Value.toggle({name:i18n("Use pruned-node adapter"),default:false}),asp_url:sdk.Value.text({name:i18n("Ark server URL"),required:true,masked:false,default:''}),rpc_url:sdk.Value.text({name:i18n("Knots RPC URL"),required:false,masked:false,default:''}),rpc_user:sdk.Value.text({name:i18n("RPC username"),required:false,masked:false,default:''}),rpc_password:sdk.Value.text({name:i18n("RPC password"),required:false,masked:true,default:''}),rotateToken:sdk.Value.toggle({name:i18n("Rotate access token"),default:false})})
export const configure=sdk.Action.withInput('configure',async()=>({name:i18n('Configure test app'),description:i18n('Configure this isolated test instance while stopped.'),warning:i18n('Experimental and unaudited. Back up before changing settings.'),allowedStatuses:'only-stopped',group:null,visibility:'enabled',access:'user'}),spec,async()=>{const saved=await store.read().once();const c=saved?.configuration?JSON.parse(saved.configuration):{};return {regtest:c.network==='regtest',pruned:!!c.pruned,asp_url:c.asp_url||'',rpc_url:c.rpc_url||'',rpc_user:c.rpc_user||'',rpc_password:c.rpc_password||'',rotateToken:false}},async({effects,input})=>{
 const old=await store.read().once();const previous=old?.configuration?JSON.parse(old.configuration):{}
 const c={...previous,network:input.regtest?'regtest':'bitcoin',pruned:input.pruned,rpc_url:(input.rpc_url||'').trim(),rpc_user:input.rpc_user||'',rpc_password:input.rpc_password||'',asp_url:(input.asp_url||'').trim(),}
 if(JSON.stringify(c).length>65536)throw new Error(i18n('Configuration too large'))
 const token=old?.token&&!input.rotateToken?old.token:utils.getDefaultString({charset:'0-9,a-f',len:64})
 const postgres=old?.postgres||utils.getDefaultString({charset:'a-z,A-Z,0-9',len:48})
 await sdk.SubContainer.withTemp(effects,{imageId:'app'},sdk.Mounts.of(),'validate-settings',async sub=>{await sub.execFail(['python3','/opt/startos/check-settings.py','wallet'],{input:JSON.stringify(c)},15000)})
 await store.merge(effects,{configuration:JSON.stringify(c),token,postgres})
 return {version:'1',title:i18n('Configuration saved'),message:i18n('Start the app. Keep this credential private.'),result:{type:'single',name:i18n('Access token'),description:null,value:Buffer.concat([Buffer.from([0]),Buffer.from(token,'hex')]).toString('base64url'),masked:true,copyable:true,qr:false}}
})
const inspect=sdk.Action.withoutInput('connection-info',async()=>({name:i18n('Connection details and funding information'),description:i18n('Connection details and funding information'),warning:i18n('Keep these details private'),allowedStatuses:'only-running',group:null,visibility:'enabled',access:'user'}),async({effects})=>{const value=await sdk.SubContainer.withTemp(effects,{imageId:'app'},sdk.Mounts.of().mountVolume({volumeId:'main',subpath:null,mountpoint:'/data',readonly:true}),'connection-info',async sub=>String((await sub.execFail(["python3", "/opt/startos/connection.py"],{},15000)).stdout));return {version:'1',title:i18n('Connection details and funding information'),message:i18n('Keep these details private'),result:{type:'single',name:i18n('Connection details and funding information'),description:null,value,masked:true,copyable:true,qr:false}}})
export const actions=sdk.Actions.of().addAction(configure).addAction(inspect)
